# Design Philosophy:
# - Lazy to debug formatting
# - Lazy to test colors
# - Easier to just use an existing color scheme and design
#
# Catppuccin Color:
# - text : whitest white text
# - surface0 : blackest black surface
# - crust : blackest black test
# 
# To install:
# wget https://raw.githubusercontent.com/cardin/starship/refs/heads/mod/docs/public/presets/toml/catppuccin-powerline.toml -O $STARSHIP_CONFIG

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
[](bg:red fg:surface0)\
$username\
$hostname\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_commit\
$git_status\
[](fg:yellow bg:green)\
$nodejs\
$java\
$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$jobs\
$memory_usage\
[](fg:lavender bg:surface0)\
$time\
[ ](fg:surface0)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
    disabled = false
    style = "bg:surface0"

[os.symbols]
    Windows = "[](fg:blue) "
    Ubuntu = "[](fg:peach) "

[username]
    show_always = true
    style_user = "bg:red fg:crust"
    style_root = "bg:red fg:bold #FFFFFF"
    format = '[ $user ]($style)'

[hostname]
    # by default only shows on SSH
    ssh_symbol = ""
    style = "bg:red fg:crust"
    format = "[[$ssh_symbol $hostname ](bg:red fg:crust)]($style)"

[directory]
    style = "bg:peach fg:crust"
    format = "[ $path ]($style)"
    truncation_length = 3
    truncation_symbol = "…/"
    read_only_style = "fg:color_red bg:peach"
    read_only = "󰌾 "

[git_branch]
    symbol = ""
    style = "bg:yellow"
    format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_commit]
    style = "bg:yellow"
    format = "[[($tag)](fg:crust bg:yellow)]($style)"

[git_status]
    style = "bg:yellow"
    format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
    symbol = ""
    style = "bg:green"
    format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
    symbol = " "
    style = "bg:green"
    format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
    symbol = ""
    style = "bg:green"
    format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:green)]($style)'

[conda]
    symbol = "  "
    style = "fg:crust bg:sapphire"
    format = '[$symbol$environment ]($style)'
    ignore_base = false

[jobs]
    symbol = "󰆅"
    style = "fg:subtext1 bg:surface0"
    format = "[ $symbol( $number)]($style)"

[memory_usage]
    symbol = "󰍛"
    style = "fg:bold red bg:surface0"
    format = "[ $symbol ${ram} ]($style)"

[time]
    disabled = false
    time_format = "%R"
    style = "bg:surface0 fg:subtext1"
    format = '[[  $time ](fg:subtext1 bg:surface0)]($style)'

[character]
    disabled = false
    success_symbol = '[❯](bold fg:green)'
    error_symbol = '[❯](bold fg:red)'
    vimcmd_symbol = '[❮](bold fg:green)'
    vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
    vimcmd_replace_symbol = '[❮](bold fg:lavender)'
    vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
    show_milliseconds = true
    format = " in $duration "
    style = "bg:surface0 fg:subtext1"
    disabled = false

[palettes.catppuccin_mocha]
    rosewater = "#f5e0dc"
    flamingo = "#f2cdcd"
    pink = "#f5c2e7"
    mauve = "#cba6f7"
    red = "#f38ba8"
    maroon = "#eba0ac"
    peach = "#fab387"
    yellow = "#f9e2af"
    green = "#a6e3a1"
    teal = "#94e2d5"
    sky = "#89dceb"
    sapphire = "#74c7ec"
    blue = "#89b4fa"
    lavender = "#b4befe"
    text = "#cdd6f4"
    subtext1 = "#bac2de"
    subtext0 = "#a6adc8"
    overlay2 = "#9399b2"
    overlay1 = "#7f849c"
    overlay0 = "#6c7086"
    surface2 = "#585b70"
    surface1 = "#45475a"
    surface0 = "#313244"
    base = "#1e1e2e"
    mantle = "#181825"
    crust = "#11111b"
